#!/bin/bash

# Create a GitHub repository for your project (if you don't already have one)
echo "=== Instructions to Deploy EcoTracker ==="
echo ""
echo "STEP 1: Create a GitHub repository"
echo "Go to https://github.com/new and create a new repository"
echo "Then initialize your local repository and push your code:"
echo ""
echo "git init"
echo "git add ."
echo "git commit -m 'Initial commit'"
echo "git branch -M main"
echo "git remote add origin https://github.com/YOURUSERNAME/YOURREPO.git"
echo "git push -u origin main"
echo ""
echo "STEP 2: Deploy the frontend to Vercel"
echo "Go to https://vercel.com/"
echo "Sign up or log in (you can use your GitHub account)"
echo "Click 'Add New...' > 'Project'"
echo "Import your GitHub repository"
echo "Configure your project:"
echo "  - Framework Preset: Vite"
echo "  - Root Directory: ecotracker"
echo "  - Build Command: npm run build"
echo "  - Output Directory: dist"
echo "Click 'Deploy'"
echo ""
echo "STEP 3: Deploy the backend"
echo "Option A - Railway.app:"
echo "  - Go to https://railway.app/"
echo "  - Sign up or log in"
echo "  - Create a new project"
echo "  - Choose 'Deploy from GitHub repo'"
echo "  - Select your repository"
echo "  - In settings, set these variables:"
echo "    - ROOT_DIRECTORY: ."
echo "    - PORT: 5050"
echo "    - RAILWAY_DOCKERFILE_PATH: Dockerfile"
echo ""
echo "Option B - Render.com:"
echo "  - Go to https://render.com/"
echo "  - Sign up or log in"
echo "  - Create a new Web Service"
echo "  - Connect your GitHub repository"
echo "  - Set the start command: 'python server.py'"
echo "  - Set environment variable: PORT=5050"
echo ""
echo "STEP 4: Update the API base URL"
echo "Once your backend is deployed, you need to update the API base URL in the frontend"
echo "Edit ecotracker/src/lib/axios.ts and change the baseURL to your backend URL"
echo ""
echo "STEP 5: Redeploy the frontend"
echo "Push your changes to GitHub and Vercel will automatically redeploy your app"
echo ""
echo "Your app will be available at your Vercel URL (usually https://your-project-name.vercel.app)"
